[package]
name = "tokio-process-pipes"
version = "0.1.0"
authors = ["Jan Algermissen <algermissen@acm.org>"]

[dependencies]
futures = "0.1.17"
tokio-core = "0.1.11"
tokio-io = "0.1.4"
tokio-process = "0.1.4"




